config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :events
  resources :playlists
  resources :tracks
  resources :kyrs
  resources :courses
  resources :categories
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  get 'main/index'
  get 'lending/index'
  get 'styleguide/index'


  resources :posts do
      resources :comments
      resources :likes
      resources :favorites
  end

  resources :tracks do
      resources :favorites
  end

  resources :playlists do
      resources :favorites
  end

  resources :events do
  	resources :comments
  end

get 'users', to: 'users#index'
get 'users/:id' => 'users#show', :as => :user
delete 'users/:id', to: 'users#destroy'

get 'tracks/index'
get 'playlists/index'

get 'events/index'
get 'groups/index'

  get 'posts/index'


  root 'main#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord

end

app/models/comment.rb
class Comment < ApplicationRecord
  	belongs_to :user
		belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
		validates :name, :presence => true
		validates :title, :presence => true,
											:length => { :minimum => 5 }

has_many :comments, :dependent => :destroy
mount_uploader :image, ImageUploader


end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/group.rb
class Group < ApplicationRecord
		validates :name, :presence => true
		validates :title, :presence => true,
											:length => { :minimum => 5 }
                      mount_uploader :image, ImageUploader
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  scope :filter_by_starts_with, -> (search) { where("name like :search or title like :search or content like :search", search: "%#{search}%")}
		validates :name, :presence => true
		validates :title, :presence => true,
											:length => { :minimum => 5 }
    mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  scope :filter_by_starts_with, -> (search) { where("name like :search or title like :search or content like :search", search: "%#{search}%")}
  scope :filter_by_user, -> (user) { where user: user }
scope :filter_by_category, -> (category) { where category: category }
scope :filter_by_starts_with, -> (name) { where("name like ?", "%#{name}%")}
		validates :name, :presence => true
		validates :title, :presence => true,
											:length => { :minimum => 5 }

		has_many :comments, :dependent => :destroy
    has_many :likes, dependent: :destroy
		mount_uploader :image, ImageUploader
    has_many :favorites, dependent: :destroy
    belongs_to :user
    belongs_to :category
end

app/models/track.rb
class Track < ApplicationRecord
	scope :filter_by_starts_with, -> (search) { where("name like :search or title like :search or content like :search", search: "%#{search}%")}
		validates :name, :presence => true
		validates :title, :presence => true,
											:length => { :minimum => 5 }
    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :likes, dependent: :destroy
         has_many :favorites, dependent: :destroy
has_many :favorited_posts, :through => :favorites, :source => :post
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with :name => "admin", :password => "superstrongpassword", :except => [:index, :show]
  before_action :set_post, only: %i[ show edit update destroy ]
before_action :authenticate_user!, except: [:index, :show]
  # GET /posts or /posts.json
  def index
    @posts = Post.where(nil)
  filtering_params(params).each do |key, value|
    @posts = @posts.public_send("filter_by_#{key}", value) if value.present?
  end
      # if params.has_key?(:category)
      #   @category = Category.find_by_name(params[:category])
      #   @posts = Post.where(category: @category)
      # else
      #   @posts = Post.all
      # end
    end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
  @post = Post.new(post_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def filtering_params(params)
  params.slice(:user, :category, :starts_with)
end
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
	params.require(:post).permit(:name, :title, :content, :image, :category_id, :gif)
end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/kyrs_helper.rb
module KyrsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>




  <div class="field">
    <h4 class="form__block__title1">Вид мероприятия</h4>
    <%= form.text_field :name, :class => "form3" %>
  </div>

  <div class="field">
      <%= form.label :category_id %>
      <%= form.select :category_id, Category.pluck(:name, :id) %>
  </div>

  <div class="field">
    <h4 class="form__block__title2">Название</h4>
    <%= form.text_field :title, :class => "form2" %>
  </div>

  <div>
    <h4 class="form__block__title4">Загрузите изображение</h4>
  </div>
  	<%= form.file_field :image, :class => "imgloader" %>

    <div>
      <h4 class="form__block__title5">Загрузите gif</h4>
    </div>
      <%= form.file_field :gif, :class => "imggloader" %>

  <div class="field">
    <h4 class="form__block__title3">Описание</h4></div>

    <div class="field">
        <%= form.label :content %>
        <%= form.cktext_area :content %>
      </div>



    <%= form.submit :class => "actions" %>


<% end %>

app/views/posts/_old_index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag posts_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :starts_with, params[:starts_with] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>


  <%= react_component 'OAllPosts', { posts: @posts } %>


<h2>Все направления</h2>
<% Category.all.each do |cat| %>
	<%= link_to cat.name, posts_path(category: cat.name) %> <br>
<% end %>
<table>

  <tbody class="posts">

    <% @posts.each do |post| %>
      <tr class="posts__item">


<td><%= post.category.name %></td>
        <td class="posts__item__text posts__item__text-theme"><%= post.name %></td>
         <td class="posts__item__text posts__item__text-title"><%= post.title %></td>
         <td><%= post.content.html_safe %></td>

         class Image < ApplicationModel
           attribute :image_url, default: default_image
         end
        <td><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></td>
        <td><%= post.comments.count %> <%= (post.comments.count) == 1 ? 'Comment' : 'Commentes'%></td>

<td class="posts__item__links">

          <%= link_to 'Открыть', post, :class =>"link" %>


        <%= link_to 'Изменить', edit_post_path(post), :class =>"link" %>


        <%= link_to 'Удалить', post, method: :delete, data: { confirm: 'Are you sure?' }, :class =>"link" %>

      </td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="actions10">
<%= link_to 'Новый пост', new_post_path %>
</div>
<%= link_to 'New Category', new_category_path %>

app/views/posts/_old_show.html.erb
<p id="notice"><%= notice %></p>
<div class="link22">
  <%= link_to "о проекте", about_path %>
</div>
<div class="link11">
  <%= link_to "промо", promo_path %>
</div>
<div class="link33">
  <%= link_to "афиша", posts_path %>
</div>

<%= react_component 'MLesson', { post: @post } %>
<div class="titlenew2">
<h1>
  <strong></strong>
  <%= @post.title %>
</h1>
</div>

<p>
  <strong>Category:</strong>
  <%= @post.category.name %>
</p>

  <strong></strong>
<h4 class="form__block__title15">  <%= @post.name %></h4>

<div class="showimg">
<%= image_tag(@post.image.url, alt: 'Image') if @post.image? %>
</div>

<% if user_signed_in? %>
  <% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
  <% if pre_like %>
    <%= button_to 'Unlike', post_like_path(@post, pre_like), method: :delete %>
  <% else %>
    <%= button_to 'Like', post_likes_path(@post), method: :post %>
  <% end %>
<% end %>
<p><%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'Like' : 'Likes'%></p>

<% pre_favorite = @post.favorites.find { |favorite| favorite.user_id == current_user.id} %>
<% if pre_favorite %>
    <%= button_to 'Remove from Favorite', post_favorite_path(@post, pre_favorite), method: :delete %>
<% else %>
    <%= button_to 'Add to Favorite', post_favorites_path(@post), method: :post %>
<% end %>

<p>
  <strong>Content:</strong>
  <%= @post.content.html_safe %>
</p>



  <strong></strong>
<h4 class="form__block__title16">   <%= @post.content %></h4>


<h4 class="form__block__title18">Комментарии</h4>
<% if user_signed_in? %>
<%= render "comments/form" %>
<% else %>
<p>Please <%= link_to 'login', new_user_session_path %> or <%= link_to 'register', new_user_registration_path %> to comment.</p>
<% end %>
<div class="back2">
<%= link_to 'Назад', posts_path %> |
</div>
<div class="show2">
  <% if user_signed_in? %>
  <%= link_to 'Редактировать', edit_post_path(@post) %> |
  <% end %>

<h4 class="form__block__title17">
Добавить комментарий:
</h4>
<%= render "comments/form" %>

app/views/posts/edit.html.erb
<div class="titlenew">
<h1>Редактирование поста</h1>
</div>
<%= render 'form', post: @post %>
<div class="show">
<%= link_to 'Показать', @post %>
</div>
<div class="back">
<%= link_to 'Назад', posts_path %> |
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag posts_path, :method => 'get' do %>
  <p class="poisk">
    <%= text_field_tag :starts_with, params[:starts_with] %>
    <%= submit_tag "Поиск", :name => nil %>
  </p>
<% end %>


  <%= react_component 'OAllPosts', { posts: @posts } %>
  <%= react_component 'MMenu' %>


  <tbody class="posts">

    <% @posts.each do |post| %>
      <tr class="posts__item"></tr>
    <% end %>

  </tbody>



<br>
<div class="actions10">
<%= link_to 'Новый пост', new_post_path %>
</div>
<div class="actions11">
<%= link_to 'New Category', new_category_path %>
</div>

app/views/posts/new.html.erb
<div class="titlenew">
  <h1>Новое мероприятие</h1>
</div>


<%= render 'form', post: @post %>
<div class="back">
<%= link_to 'Назад', posts_path %>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>


<%= react_component 'MLesson', { post: @post } %>
<div class="youtube">
  <iframe width="560" height="315" src="https://www.youtube.com/embed/32si5cfrCNc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

  <%= form_tag posts_path, :method => 'get' do %>
  <p class="poisk">
    <%= text_field_tag :starts_with, params[:starts_with] %>
    <%= submit_tag "Поиск", :name => nil %>
  </p>
<% end %>


  <%= react_component 'MMenu' %>

<div class="buufa">

<% pre_favorite = @post.favorites.find { |favorite| favorite.user_id == current_user.id} %>
<% if pre_favorite %>
    <%= button_to 'Remove from Favorite', post_favorite_path(@post, pre_favorite), method: :delete %>
<% else %>
    <%= button_to 'Add to Favorite', post_favorites_path(@post), method: :post %>
<% end %>

</div>



<div class="back2">
<%= link_to 'Назад', posts_path %> |
</div>
<div class="show2">
  <% if user_signed_in? %>
  <%= link_to 'Редактировать', edit_post_path(@post) %> |
  <% end %>