config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :events
  resources :playlists
  resources :tracks
  resources :kyrs
  resources :courses
  resources :categories
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  get 'main/index'
  get 'lending/index'
  get 'styleguide/index'


  resources :posts do
      resources :comments
      resources :likes
      resources :favorites
  end

  resources :tracks do
      resources :favorites
  end

  resources :playlists do
      resources :favorites
  end

  resources :events do
  	resources :comments
  end

get 'users', to: 'users#index'
get 'users/:id' => 'users#show', :as => :user
delete 'users/:id', to: 'users#destroy'

get 'tracks/index'
get 'playlists/index'

get 'events/index'
get 'groups/index'

  get 'posts/index'


  root 'main#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord

end

app/models/comment.rb
class Comment < ApplicationRecord
  	belongs_to :user
		belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
		validates :name, :presence => true
		validates :title, :presence => true,
											:length => { :minimum => 5 }

has_many :comments, :dependent => :destroy
mount_uploader :image, ImageUploader


end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/group.rb
class Group < ApplicationRecord
		validates :name, :presence => true
		validates :title, :presence => true,
											:length => { :minimum => 5 }
                      mount_uploader :image, ImageUploader
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  scope :filter_by_starts_with, -> (search) { where("name like :search or title like :search or content like :search", search: "%#{search}%")}
		validates :name, :presence => true
		validates :title, :presence => true,
											:length => { :minimum => 5 }
    mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  scope :filter_by_starts_with, -> (search) { where("name like :search or title like :search or content like :search", search: "%#{search}%")}
  scope :filter_by_user, -> (user) { where user: user }
scope :filter_by_category, -> (category) { where category: category }
scope :filter_by_starts_with, -> (name) { where("name like ?", "%#{name}%")}
		validates :name, :presence => true
		validates :title, :presence => true,
											:length => { :minimum => 5 }

		has_many :comments, :dependent => :destroy
    has_many :likes, dependent: :destroy
		mount_uploader :image, ImageUploader
    has_many :favorites, dependent: :destroy
    belongs_to :user
    belongs_to :category
end

app/models/track.rb
class Track < ApplicationRecord
	scope :filter_by_starts_with, -> (search) { where("name like :search or title like :search or content like :search", search: "%#{search}%")}
		validates :name, :presence => true
		validates :title, :presence => true,
											:length => { :minimum => 5 }
    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :likes, dependent: :destroy
         has_many :favorites, dependent: :destroy
has_many :favorited_posts, :through => :favorites, :source => :post
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: %i[ show edit update destroy ]
  http_basic_authenticate_with :name => "admin", :password => "superstrongpassword", :except => [:index, :show]

  # GET /playlists or /playlists.json
  def index
    @playlists = Playlist.all
  end

  # GET /playlists/1 or /playlists/1.json
  def show
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists or /playlists.json
  def create
    @playlist = Playlist.new(playlist_params)

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to playlist_url(@playlist), notice: "Playlist was successfully created." }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists/1 or /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to playlist_url(@playlist), notice: "Playlist was successfully updated." }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1 or /playlists/1.json
  def destroy
    @playlist.destroy

    respond_to do |format|
      format.html { redirect_to playlists_url, notice: "Playlist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def playlist_params
      params.require(:playlist).permit(:name, :title, :content, :image)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/kyrs_helper.rb
module KyrsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/playlists/_form.html.erb
<%= form_with(model: playlist) do |form| %>
  <% if playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
        <% playlist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
    <div>
  	<%= form.label :image %>
  	<%= form.file_field :image %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/playlists/edit.html.erb
<h1>Editing Playlist</h1>

<%= render 'form', playlist: @playlist %>

<%= link_to 'Show', @playlist %> |
<%= link_to 'Back', playlists_path %>

app/views/playlists/index.html.erb
<p id="notice"><%= notice %></p>
<%= form_tag posts_path, :method => 'get' do %>
  <p class="poisk">
    <%= text_field_tag :starts_with, params[:starts_with] %>
    <%= submit_tag "Поиск", :name => nil %>
  </p>
<% end %>
  <%= react_component 'MMenu' %>
  <%= react_component 'OAllPlaylist', { playlists: @playlists } %>

<table style="position: absolute; top:100vw;">
  <thead>
    <tr>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @playlists.each do |playlist| %>
      <tr>
        <td><%= playlist.name %></td>
        <td><%= playlist.title %></td>

            <td><%= playlist.content %></td>
        <td><%= link_to 'Show', playlist %></td>
        <td><%= link_to 'Edit', edit_playlist_path(playlist) %></td>
        <td><%= link_to 'Destroy', playlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div style="position: absolute; top:100vw">
  <%= link_to 'New Playlist', new_playlist_path %>

</div>

app/views/playlists/new.html.erb
<h1>New Playlist</h1>

<%= render 'form', playlist: @playlist %>

<%= link_to 'Back', playlists_path %>

app/views/playlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @playlist.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @playlist.title %>
</p>
<%= link_to(image_tag(@playlist.image.thumb.url, alt: 'Image'), @playlist.image.url, target: '_blank') if @playlist.image? %>

<%= link_to 'Edit', edit_playlist_path(@playlist) %> |
<%= link_to 'Back', playlists_path %>